=== 360cloud/configuration-as-code-plugin/src/main/resources/schema/jenkins.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "javaType": "org.jenkinsci.plugins.systemconfigdsl.impl.jenkins.generated.JenkinsConfig",
  "javaInterfaces" : ["org.jenkinsci.plugins.systemconfigdsl.api.ConfigurationDescription"],
  "properties": {
    "numExecutorsOnMaster": {
      "type": "integer"
    },
    "scmQuietPeriod": {
      "type": "integer"
    },
    "scmCheckoutRetryCount": {
      "type": "integer"
    },
    "jenkinsRootUrl": {
      "type": "string"
    },
    "jenkinsAdminEmail": {
      "type": "string"
    },
    "variables": {
      "type": "array",
      "items": {
        "type": "object",
        "javaType": "org.jenkinsci.plugins.systemconfigdsl.impl.jenkins.generated.EnvVariable",
        "properties": {
          "name": {
            "type": "string"
          },
          "value": {
            "type": "string"
          }
        },
        "additionalProperties": false,
        "required": [
          "name",
          "value"
        ]
      }
    },
    "smtp": {
      "type": "object",
      "javaType": "org.jenkinsci.plugins.systemconfigdsl.impl.jenkins.generated.SmtpConfig",
      "properties": {
        "enabled": {
          "type": "boolean"
        },
        "host": {
          "type": "string"
        },
        "port": {
          "type": "integer"
        },
        "reply_to_address": {
          "type": "string"
        },
        "authentication": {
          "type": "object",
          "javaType": "org.jenkinsci.plugins.systemconfigdsl.impl.jenkins.generated.SmtpAuthConfig",
          "properties": {
            "enabled": {
              "type": "boolean"
            },
            "login": {
              "type": "string"
            },
            "passwordFile": {
              "type": "string"
            }
          },
          "additionalProperties": false,
          "required": [
            "enabled"
          ]
        },
        "additionalProperties": false,
        "required": [
          "enabled"
        ]
      },
      "additionalProperties": false,
      "required": [
        "enabled"
      ]
    }
  },
  "additionalProperties": false
}

=== 360cloud/configuration-as-code-plugin/src/main/resources/examples/jenkins.json
{
  "numExecutorsOnMaster": 0,
  "scmQuietPeriod": 3,
  "scmCheckoutRetryCount": 3,
  "jenkinsRootUrl": "",
  "jenkinsAdminEmail": "Jenkins <no-reply@yourcompany.com>",
  "variables": [
    {
      "name": "default_credentials",
      "value": "jenkins"
    },
    {
      "name": "default_repo",
      "value": "git@github.com:Praqma/JenkinsAsCodeReference.git"
    },
    {
      "name": "default_branch",
      "value": "master"
    },
    {
      "name": "default_registry_url",
      "value": "localhost:5000"
    },
    {
      "name": "default_registry_credId",
      "value": "jenkins"
    },
    {
      "name": "utility_slave",
      "value": "utility-slave"
    },
    {
      "name": "master_image_name",
      "value": ""
    },
    {
      "name": "slave_image_name",
      "value": ""
    }
  ],
  "smtp": {
    "enabled": false,
    "host": "1.1.1.1",
    "port": 25,
    "reply_to_address": "no-reply@yourcompany.com",
    "authentication": {
      "enabled": true,
      "login": "jenkins",
      "passwordFile": "/var/jenkins_home/.ssh/.smtp_password"
    }
  }
}
